
package com.zj.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CxfWebService", targetNamespace = "http://server.zj.com/", wsdlLocation = "http://10.129.69.114:8080/server?wsdl")
public class CxfWebService
    extends Service
{

    private final static URL CXFWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CXFWEBSERVICE_EXCEPTION;
    private final static QName CXFWEBSERVICE_QNAME = new QName("http://server.zj.com/", "CxfWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.129.69.114:8080/server?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CXFWEBSERVICE_WSDL_LOCATION = url;
        CXFWEBSERVICE_EXCEPTION = e;
    }

    public CxfWebService() {
        super(__getWsdlLocation(), CXFWEBSERVICE_QNAME);
    }

    public CxfWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CXFWEBSERVICE_QNAME, features);
    }

    public CxfWebService(URL wsdlLocation) {
        super(wsdlLocation, CXFWEBSERVICE_QNAME);
    }

    public CxfWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CXFWEBSERVICE_QNAME, features);
    }

    public CxfWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CxfWebServicePortType
     */
    @WebEndpoint(name = "CxfWebServicePort")
    public CxfWebServicePortType getCxfWebServicePort() {
        return super.getPort(new QName("http://server.zj.com/", "CxfWebServicePort"), CxfWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfWebServicePortType
     */
    @WebEndpoint(name = "CxfWebServicePort")
    public CxfWebServicePortType getCxfWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.zj.com/", "CxfWebServicePort"), CxfWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CXFWEBSERVICE_EXCEPTION!= null) {
            throw CXFWEBSERVICE_EXCEPTION;
        }
        return CXFWEBSERVICE_WSDL_LOCATION;
    }

}
