package cn.itcast.cxf.spring.call;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-05-30T10:48:08.915+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://call.spring.cxf.itcast.cn/", name = "CallService")
@XmlSeeAlso({ObjectFactory.class})
public interface CallService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "makeCaller", targetNamespace = "http://call.spring.cxf.itcast.cn/", className = "cn.itcast.cxf.spring.call.MakeCaller")
    @WebMethod
    @ResponseWrapper(localName = "makeCallerResponse", targetNamespace = "http://call.spring.cxf.itcast.cn/", className = "cn.itcast.cxf.spring.call.MakeCallerResponse")
    public boolean makeCaller(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
